### ISSUE TITLE
AttributeError: module 'regex' has no attribute 'Pattern' after upgrading Black 21.10b0 to 21.11b0

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#437]
[Files changed](https://github.com/linz/geostore/pull/1210/files):

```
diff --git a/poetry.lock b/poetry.lock
index 178c6bd..622e7c7 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -1235,7 +1235,7 @@ python-versions = "*"
 
 [[package]]
 name = "black"
-version = "21.10b0"
+version = "21.11b0"
 description = "The uncompromising code formatter."
 category = "dev"
 optional = false
@@ -3153,8 +3153,8 @@ backcall = [
     {file = "backcall-0.2.0.tar.gz", hash = "sha256:5cbdbf27be5e7cfadb448baf0aa95508f91f2bbc6c6437cd9cd06e2a4c215e1e"},
 ]
 black = [
-    {file = "black-21.10b0-py3-none-any.whl", hash = "sha256:6eb7448da9143ee65b856a5f3676b7dda98ad9abe0f87fce8c59291f15e82a5b"},
-    {file = "black-21.10b0.tar.gz", hash = "sha256:a9952229092e325fe5f3dae56d81f639b23f7131eb840781947e4b2886030f33"},
+    {file = "black-21.11b0-py3-none-any.whl", hash = "sha256:0b1f66cbfadcd332ceeaeecf6373d9991d451868d2e2219ad0ac1213fb701117"},
+    {file = "black-21.11b0.tar.gz", hash = "sha256:83f3852301c8dcb229e9c444dd79f573c8d31c7c2dad9bbaaa94c808630e32aa"},
 ]
 boto3 = [
     {file = "boto3-1.17.53-py2.py3-none-any.whl", hash = "sha256:3bf3305571f3c8b738a53e9e7dcff59137dffe94670046c084a17f9fa4599ff3"},
```

[Build output](https://github.com/linz/geostore/runs/4236820134?check_suite_focus=true):

```text
Traceback (most recent call last):
  File "/home/runner/work/geostore/geostore/.venv/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/__init__.py", line 39, in <module>
    from black.nodes import STARS, syms, is_simple_decorator_expression
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/nodes.py", line 31, in <module>
    from black.strings import has_triple_quotes
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/strings.py", line 159, in <module>
    def _cached_compile(pattern: str) -> re.Pattern:
AttributeError: module 'regex' has no attribute 'Pattern'
Traceback (most recent call last):
  File "/home/runner/work/geostore/geostore/.venv/bin/black", line 5, in <module>
    from black import patched_main
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/__init__.py", line 39, in <module>
    from black.nodes import STARS, syms, is_simple_decorator_expression
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/nodes.py", line 31, in <module>
    from black.strings import has_triple_quotes
  File "/home/runner/work/geostore/geostore/.venv/lib/python3.8/site-packages/black/strings.py", line 159, in <module>
    def _cached_compile(pattern: str) -> re.Pattern:
AttributeError: module 'regex' has no attribute 'Pattern'
```

**Comment by adisbladis** [comment]
This is not an issue with poetry2nix, but an upstream one https://github.com/psf/black/issues/2623.
